---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-operator-deployment
  labels:
    app.kubernetes.io/name: hive-operator
    app.kubernetes.io/instance: hive-operator
    app.kubernetes.io/version: "0.8.0-nightly"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: hive-operator
      app.kubernetes.io/instance: hive-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hive-operator
        app.kubernetes.io/instance: hive-operator
    spec:
      serviceAccountName: hive-operator-serviceaccount
      securityContext: {}
      containers:
        - name: hive-operator
          securityContext: {}
          image: "docker.stackable.tech/stackable/hive-operator:0.8.0-nightly"
          imagePullPolicy: IfNotPresent
          resources: {}
          volumeMounts:
            - mountPath: /etc/stackable/hive-operator/config-spec
              name: config-spec
      volumes:
        - name: config-spec
          configMap:
            name: hive-operator-configmap
