---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hive-operator-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - services
      - endpoints
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - command.hive.stackable.tech
    resources:
      - inits
      - restarts
      - starts
      - stops
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - command.hive.stackable.tech
    resources:
      - inits/status
    verbs:
      - patch
  - apiGroups:
      - hive.stackable.tech
    resources:
      - hiveclusters
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - hive.stackable.tech
    resources:
      - hiveclusters/status
    verbs:
      - patch
