---
# Source: hive-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hive-operator-serviceaccount
  labels:
    helm.sh/chart: hive-operator-0.7.0-nightly
    app.kubernetes.io/name: hive-operator
    app.kubernetes.io/instance: hive-operator
    app.kubernetes.io/version: "0.7.0-nightly"
    app.kubernetes.io/managed-by: Helm
---
# Source: hive-operator/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: hive-operator-clusterrolebinding
  labels:
    helm.sh/chart: hive-operator-0.7.0-nightly
    app.kubernetes.io/name: hive-operator
    app.kubernetes.io/instance: hive-operator
    app.kubernetes.io/version: "0.7.0-nightly"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: hive-operator-serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: hive-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
