[package]
authors = ["Lars Francke <lars.francke@stackable.de>"]
description = "Stackable Operator for Apache Hive"
edition = "2018"
license = "OSL-3.0"
name = "stackable-hive-operator-binary"
repository = "https://github.com/stackabletech/hive-operator"
version = "0.2.0-nightly"
build = "build.rs"

[dependencies]
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.3.0" }
stackable-hive-crd = { path = "../crd" }
stackable-hive-operator = { path = "../operator" }

clap = "2.33"
tokio = { version = "1.13", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"

[build-dependencies]
built = { version =  "0.5", features = ["chrono", "git2"] }
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.3.0" }
stackable-hive-crd = { path = "../crd" }

[package.metadata.deb]
name = "stackable-hive-operator"
maintainer-scripts = "../../packaging/debian/"
systemd-units = { enable = false, unit-name = "stackable-hive-operator" }
assets = [
    ["../../target/release/stackable-hive-operator", "opt/stackable/hive-operator/", "755"],
    ["../../deploy/crd/hivecluster.crd.yaml", "etc/stackable/hive-operator/crd/", "644"],
    ["../../deploy/crd/databaseconnection.crd.yaml", "etc/stackable/hive-operator/crd/", "644"],
    ["../../deploy/crd/restart.crd.yaml", "etc/stackable/hive-operator/crd/", "644"],
    ["../../deploy/crd/start.crd.yaml", "etc/stackable/hive-operator/crd/", "644"],
    ["../../deploy/crd/stop.crd.yaml", "etc/stackable/hive-operator/crd/", "644"],
    ["../../deploy/config-spec/properties.yaml", "etc/stackable/hive-operator/config-spec/", "644"],
]

[[bin]]
name = "stackable-hive-operator"
path = "src/stackable-hive-operator.rs"
