---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: aws-eks
metadata:
  name: hive-operator-integration-tests
  description: "Cluster for Hive Operator Integration Tests (AWS EKS)"
publicKeys: []
spec:
  region: "eu-central-1"
  awsInstanceType: "t2.medium"
  versions:
    _-operator: NIGHTLY
    hive-operator: "$HIVE_OPERATOR_VERSION"
  node_count: 3
