version: 0.1.0
spec:
  units:
    - unit: &unitPort
        name: "port"
        regex: "^([0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$"
    - unit: &unitUri
        name: "uri"
        regex: "^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?"
        examples:
          - "ldap://[2001:db8::7]/c=GB?objectClass?one"
        comment: "Specified in https://tools.ietf.org/html/rfc3986#appendix-B"
    - unit: &unitDirectory
        name: "directory"
        regex: "^/|(/[\\w-]+)+$"
        examples:
          - "/tmp/xyz"

properties:
  - property:
      propertyNames:
        - name: "javax.jdo.option.ConnectionURL"
          kind:
            type: "file"
            file: "hive-site.xml"
      datatype:
        type: "string"
      roles:
        - name: "metastore"
          required: true
      asOfVersion: "0.0.0"
      description: "JDBC connect string for a JDBC metastore.
      To use SSL to encrypt/authenticate the connection, provide database-specific SSL flag in the connection URL.
      For example, jdbc:postgresql://myhost/db?ssl=true for postgres database."
  - property:
      propertyNames:
        - name: "javax.jdo.option.ConnectionDriverName"
          kind:
            type: "file"
            file: "hive-site.xml"
      datatype:
        type: "string"
      roles:
        - name: "metastore"
          required: true
      asOfVersion: "0.0.0"
  - property:
      propertyNames:
        - name: "javax.jdo.option.ConnectionUserName"
          kind:
            type: "file"
            file: "hive-site.xml"
      datatype:
        type: "string"
      roles:
        - name: "metastore"
          required: true
      asOfVersion: "0.0.0"
  - property:
      propertyNames:
        - name: "javax.jdo.option.ConnectionPassword"
          kind:
            type: "file"
            file: "hive-site.xml"
      datatype:
        type: "string"
      roles:
        - name: "metastore"
          required: true
      asOfVersion: "0.0.0"
  ###################################################################################################
  # env vars
  ###################################################################################################
  - property: &javaHome
      propertyNames:
        - name: "JAVA_HOME"
          kind:
            type: "env"
      datatype:
        type: "string"
        unit: *unitDirectory
      roles:
        - name: "metastore"
          required: true
      asOfVersion: "0.0.0"
      description: "Points to the Java installation folder."