version: 0.1.0
spec:
  units:
    - unit: &unitPort
        name: "port"
        regex: "^([0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$"
    - unit: &unitUri
        name: "uri"
        regex: "^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?"
        examples:
          - "ldap://[2001:db8::7]/c=GB?objectClass?one"
        comment: "Specified in https://tools.ietf.org/html/rfc3986#appendix-B"

properties:
  - property:
      propertyNames:
        - name: "dfs.namenode.name.dir"
          kind:
            type: "file"
            file: "hive-site.xml"
      datatype:
        type: "string"
        unit: *unitUri
      roles:
        - name: "namenode"
          required: true
        - name: "datanode"
          required: true
      asOfVersion: "0.0.0"
      description: "Determines where on the local filesystem the DFS name node should store the name table(fsimage). If this is a comma-delimited list of directories then the name table is replicated in all of the directories, for redundancy."

  - property:
      propertyNames:
        - name: "dfs.datanode.data.dir"
          kind:
            type: "file"
            file: "hive-site.xml"
      datatype:
        type: "string"
        unit: *unitUri
      roles:
        - name: "namenode"
          required: true
        - name: "datanode"
          required: true
      asOfVersion: "0.0.0"
      description: "Determines where on the local filesystem an DFS data node should store its blocks. If this is a comma-delimited list of directories, then data will be stored in all named directories, typically on different devices. Directories that do not exist are ignored."

  - property:
      propertyNames:
        - name: "dfs.replication"
          kind:
            type: "file"
            file: "hive-site.xml"
      datatype:
        type: "integer"
        min: "1"
        max: "512"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "3"
      roles:
        - name: "namenode"
          required: true
        - name: "datanode"
          required: true
      asOfVersion: "0.0.0"
      description: "Default block replication. The actual number of replications can be specified when the file is created. The default is used if replication is not specified in create time."
  - property:
      propertyNames:
        - name: "fs.defaultFS"
          kind:
            type: "file"
            file: "core-site.xml"
      datatype:
        type: "string"
        unit: *unitUri
      defaultValues:
        - fromVersion: "0.0.0"
          value: "file:///"        
      roles:
        - name: "namenode"
          required: true
        - name: "datanode"
          required: true
      asOfVersion: "0.0.0"
      description: "The name of the default file system. A URI whose scheme and authority determine the FileSystem implementation. The uri's scheme determines the config property (fs.SCHEME.impl) naming the FileSystem implementation class. The uri's authority is used to determine the host, port, etc. for a filesystem."
