:clusterName: simple-hive-derby
:namespace: stackable
:metastorePort: 9083

= Discovery Profiles

The Stackable Operator for Apache Hive creates a single discovery profile that allows access to the Hive metastore which is published into the Kubernetes cluster as a
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#configmap-v1-core[`ConfigMap`] object.

== Profiles

Given the following Hive cluster:

[subs="attributes"]
----
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: {clusterName} # <1>
  namespace: {namespace} # <2>
spec:
  [...]
----
<1> Name of the Hive cluster which is the name of the `ConfigMap` created for this discovery profile.
<2> Namespace of the `ConfigMap` created for this discovery profile.

The published `ConfigMap` name and namespace are equal to the cluster name and namespace. In this case `{namespace}/{clusterName}`.

=== Default

This profile allows access to the Hive cluster from inside the Kubernetes cluster, and connects directly to the metastore NodePort `Service`.

== Contents

The discovery profile contains the following fields where `{clusterName}` represents the name and `{namespace}` the namespace of the cluster:

`HIVE`::
====
Contains the thrift protocol connection string for the Hive cluster to connect to the metastore:
[subs="attributes"]
  thrift://{clusterName}-metastore-default-0.{clusterName}-metastore-default.{namespace}.svc.cluster.local:{metastorePort}

or

[subs="attributes"]
  thrift://{clusterName}-metastore-default-0.{clusterName}-metastore-default.{namespace}.svc.cluster.local:{metastorePort}
  thrift://{clusterName}-metastore-default-1.{clusterName}-metastore-default.{namespace}.svc.cluster.local:{metastorePort}

for rolegroup `replicas` greater than one (two in this case), which should be avoided since the metastore instances do not sync between each other.
====
