= Installation

There are three ways to run the Stackable Operator for Apache Hive:

1. Helm managed Docker container deployment on Kubernetes

2. As a Docker container

3. Build from source.

== Helm

Helm allows you to download and deploy Stackable operators on Kubernetes and is by far the easiest
installation method. First ensure that you have installed the Stackable Operators Helm repository:
[source,bash]
----
$ helm repo add stackable https://repo.stackable.tech/repository/helm-stable/
----

Then install the Stackable Operator for Apache Hive
[source,bash]
----
$ helm install hive-operator stackable/hive-operator
----

Helm will deploy the operator in a Kubernetes container and apply the CRDs for the Apache Hive
service. You are now ready to deploy Apache Hive in Kubernetes.

== Docker

This Operator is published as a Docker image:

[source]
----
docker.stackable.tech/stackable/hive-operator
----

When installing manually with Docker you will need to install the Stackable CRDs for Apache Hive
in your Kubernetes environment. These are available on the
https://github.com/stackabletech/hive-operator/tree/main/deploy/crd[Stackable GitHub repository]
for this operator.
[source]
----
$ kubectl apply -f hivecluster.crd.yaml
----

To run it straight from Docker you can use this command:
[source,bash]
----
docker run \
    --name hive-operator \
    --network host \
    --env KUBECONFIG=/home/stackable/.kube/config \
    --mount type=bind,source="$HOME/.kube/config",target="/home/stackable/.kube/config" \
    docker.stackable.tech/stackable/hive-operator:latest
----

== Building the operator from source

This operator is written in Rust and is developed against the latest stable Rust release (1.57 at the time of writing).

[source]
----
stackable-hive-operator crd | kubectl apply -f -
stackable-hive-operator run
----
