= Usage

After installation, ensure that the CRD for this operator exists or create yourself:

    kubectl apply -f /etc/stackable/hive-operator/crd/hivecluster.crd.yaml

To create a single node Apache Hive Metastore (v2.3.9) cluster with derby:

    cat <<EOF | kubectl apply -f -
    apiVersion: hive.stackable.tech/v1alpha1
    kind: HiveCluster
    metadata:
      name: simple-hive-derby
    spec:
      version: 2.3.9
      metastore:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/os: linux
            replicas: 1
            config:
              database:
                connString: jdbc:derby:;databaseName=/tmp/metastore_db;create=true
                user: APP
                password: mine
                dbType: derby
    EOF

To create a single node Apache Hive Metastore (v2.3.9) cluster with derby and S3 access:

    cat <<EOF | kubectl apply -f -
    apiVersion: hive.stackable.tech/v1alpha1
    kind: HiveCluster
    metadata:
      name: simple-hive-derby
    spec:
      version: 2.3.9
      metastore:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/os: linux
            replicas: 1
            config:
              database:
                connString: jdbc:derby:;databaseName=/stackable/metastore_db;create=true
                user: APP
                password: mine
                dbType: derby
              s3Connection:
                endPoint: changeme
                accessKey: changeme
                secretKey: changeme
                sslEnabled: false
                pathStyleAccess: true
    EOF

To create a single node Apache Hive Metastore (v2.3.9) cluster with PostgreSQL:

    apiVersion: hive.stackable.tech/v1alpha1
    kind: HiveCluster
    metadata:
      name: simple-hive-postgres
    spec:
      version: 2.3.9
      metastore:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/os: linux
            replicas: 1
            config:
              warehouseDir: /stackable/metastore
              database:
                connString: jdbc:postgresql://localhost:5432/metastoredb
                user: hiveuser
                password: mypass
                dbType: postgres
    EOF

== Configuration & Environment Overrides

The cluster definition also supports overriding configuration properties and environment variables, either per role or per role group, where the more specific override (role group) has precedence over the less specific one (role).

IMPORTANT: Overriding certain properties which are set by operator (such as the HTTP port) can interfere with the operator and can lead to problems.

=== Configuration Properties

For a role or role group, at the same level of `config`, you can specify: `configOverrides` for the `hive-site.xml`. For example, if you want to set the `datanucleus.connectionPool.maxPoolSize` for the metastore to 20 adapt the `metastore` section of the cluster resource like so:

[source,yaml]
----
metastore:
  roleGroups:
    default:
      config: [...]
      configOverrides:
        hive-site.xml:
          datanucleus.connectionPool.maxPoolSize: "20"
      replicas: 1
----

Just as for the `config`, it is possible to specify this at role level as well:

[source,yaml]
----
metastore:
  configOverrides:
    hive-site.xml:
      datanucleus.connectionPool.maxPoolSize: "20"
  roleGroups:
    default:
      config: [...]
      replicas: 1
----

All override property values must be strings. The properties will be formatted and escaped correctly into the XML file.

For a full list of configuration options we refer to the Hive https://cwiki.apache.org/confluence/display/hive/configuration+properties[Configuration Reference].

=== Environment Variables

In a similar fashion, environment variables can be (over)written. For example per role group:

[source,yaml]
----
routers:
  roleGroups:
    default:
      config: {}
      envOverrides:
        MY_ENV_VAR: "MY_VALUE"
      replicas: 1
----

or per role:

[source,yaml]
----
routers:
  envOverrides:
    MY_ENV_VAR: "MY_VALUE"
  roleGroups:
    default:
      config: {}
      replicas: 1
----


// cliOverrides don't make sense for this operator, so the feature is omitted for now