apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple
spec:
  version: 2.3.9
  metastore:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/arch
              values:
                - stackable-linux
        replicas: 1
        config:
          javaHome: /usr/lib/jvm/java-11-openjdk-amd64/
          database:
            connString: jdbc:derby:;databaseName=/home/felix/work/Stackable/metastore_db;create=true
            user: APP
            password: mine
            dbType: derby