apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple-postgres
spec:
  version: 2.3.9
  metastore:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          warehouseDir: /stackable/metastore
          database:
            connString: jdbc:postgresql://localhost:5432/metastoredb
            user: hiveuser
            password: mypass
            dbType: postgres