# helm install secret-operator \
#     oci://oci.stackable.tech/sdp-charts/secret-operator
# helm install minio \
#     minio \
#     --repo https://charts.bitnami.com/bitnami \
#     --set image.repository=bitnamilegacy/minio \
#     --set clientImage.repository=bitnamilegacy/minio-client \
#     --set defaultInitContainers.volumePermissions.image.repository=bitnamilegacy/os-shell \
#     --set console.image.repository=bitnamilegacy/minio-object-browser \
#     --set global.security.allowInsecureImages=true \
#     --set auth.rootUser=minio-access-key \
#     --set auth.rootPassword=minio-secret-key
# helm install hive bitnami/postgresql --version=12.1.5 \
# --set image.repository=bitnamilegacy/postgresql \
# --set volumePermissions.image.repository=bitnamilegacy/os-shell \
# --set metrics.image.repository=bitnamilegacy/postgres-exporter \
# --set global.security.allowInsecureImages=true \
# --set postgresqlUsername=hive \
# --set postgresqlPassword=hive \
# --set postgresqlDatabase=hive
---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple-hive-postgres
spec:
  image:
    productVersion: 4.0.1
    stackableVersion: 0.0.0-dev
  clusterConfig:
    database:
      connString: jdbc:derby:;databaseName=/tmp/hive;create=true
      credentialsSecret: hive-credentials
      dbType: derby
    s3:
      inline:
        host: test-minio
        port: 9000
        accessStyle: Path
        credentials:
          secretClass: simple-hive-s3-secret-class
  metastore:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: simple-hive-s3-secret-class
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-hive-s3-secret
  labels:
    secrets.stackable.tech/class: simple-hive-s3-secret-class
stringData:
  accessKey: minio-access-key
  secretKey: minio-secret-key
---
apiVersion: v1
kind: Secret
metadata:
  name: hive-credentials
type: Opaque
stringData:
  username: APP
  password: mine
