apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple-hive-postgres
spec:
  version: 2.3.9
  s3:
    inline:
      host: CHANGE_ME
      secretClass: simple-hive-s3-secret
  metastore:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          database:
            connString: jdbc:postgresql://hive-postgresql.default.svc.cluster.local:5432/hive
            user: hive
            password: hive
            dbType: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-hive-s3-secret
type: kubernetes.io/opaque
stringData:
  accessKeyId: YOUR_ACCESS_KEY
  secretKeyId: YOUR_SECRET_KEY
