apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple-derby
spec:
  version: 2.3.9
  metastore:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/arch
              values:
                - stackable-linux
        replicas: 1
        config:
          javaHome: /usr/lib/jvm/java-11-openjdk-amd64/
          metricsPort: 11111
          database:
            connString: jdbc:derby:;databaseName=/tmp/metastore_db;create=true
            user: APP
            password: mine
            dbType: derby
          s3Connection:
            endPoint: s3-de-central.profitbricks.com
            accessKey: 00c6d2f2d6c0a460aab7
            secretKey: d2WzGCD4zSYNOwAK9leXMtWP0/KcZpCbLjTg8zwf
            sslEnabled: false
            pathStyleAccess: true