apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple-hive-derby
spec:
  version: 2.3.9
  s3:
    inline:
      host: CHANGE_ME
      secretClass: simple-hive-s3-secret
  metastore:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          database:
            connString: jdbc:derby:;databaseName=/stackable/hive;create=true
            user: APP
            password: mine
            dbType: derby
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-hive-s3-secret
type: kubernetes.io/opaque
stringData:
  accessKeyId: YOUR_ACCESS_KEY
  secretKeyId: YOUR_SECRET_KEY
