---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple-hive-derby
spec:
  image:
    productVersion: 3.1.3
    stackableVersion: 0.0.0-dev
  clusterConfig:
    database:
      connString: jdbc:derby:;databaseName=/tmp/hive;create=true
      user: APP
      password: mine
      dbType: derby
  metastore:
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              min: 300m
              max: "2"
            memory:
              limit: 5Gi
