apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple
spec:
  version: 3.1.1
  metastore:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/arch
              values:
                - stackable-linux
        replicas: 3