apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple-postgres
spec:
  version: 2.3.9
  metastore:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/arch
              values:
                - stackable-linux
        replicas: 1
        config:
          javaHome: /usr/lib/jvm/java-11-openjdk-amd64/
          database:
            connString: jdbc:postgresql://localhost:5432/metastoredb
            user: hiveuser
            password: mypass
            dbType: postgres