apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple
spec:
  version: 3.2.2
  namenodes:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/hostname
              values:
                - main-1.stackable.demo
  datanodes:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/hostname
              values:
                - worker-1.stackable.demo
                - worker-2.stackable.demo
                - worker-3.stackable.demo
        replicas: 2