apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple-hive-postgres
spec:
  version: 2.3.9
  metastore:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          database:
            connString: jdbc:postgresql://hive-postgresql.default.svc.cluster.local:5432/hive
            user: hive
            password: hive
            dbType: postgres
          s3Connection:
            endPoint: changeme
            accessKey: changeme
            secretKey: changeme
            sslEnabled: false
            pathStyleAccess: true
