# helm install secret-operator \
#     secret-operator \
#     --repo https://repo.stackable.tech/repository/helm-stable
# helm install minio \
#     minio \
#     --repo https://charts.bitnami.com/bitnami \
#     --set auth.rootUser=minio-access-key \
#     --set auth.rootPassword=minio-secret-key
# helm install hive bitnami/postgresql --version=10 \
# --set postgresqlUsername=hive \
# --set postgresqlPassword=hive \
# --set postgresqlDatabase=hive
---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple-hive-postgres
spec:
  version: 2.3.9-stackable0.4.0
  s3:
    inline:
      host: test-minio
      port: 9000
      accessStyle: Path
      credentials:
        secretClass: simple-hive-s3-secret-class
  metastore:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          database:
            connString: jdbc:postgresql://hive-postgresql.default.svc.cluster.local:5432/hive
            user: hive
            password: hive
            dbType: postgres
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: simple-hive-s3-secret-class
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-hive-s3-secret
  labels:
    secrets.stackable.tech/class: simple-hive-s3-secret-class
stringData:
  accessKey: minio-access-key
  secretKey: minio-secret-key
