---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple-hive-derby
spec:
  version: 2.3.9-stackable0.6.0
  metastore:
    roleGroups:
      default:
        replicas: 1
        config:
          database:
            connString: jdbc:derby:;databaseName=/tmp/hive;create=true
            user: APP
            password: mine
            dbType: derby
          resources:
            storage:
              data:
                capacity: 5Gi
            cpu:
              min: 300m
              max: "2"
            memory:
              limit: 5Gi
