---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-postgres-s3
spec:
  image:
    productVersion: 4.2.0
  clusterConfig:
    metadataDatabase:
      postgresql:
        host: postgresql
        database: hive
        credentialsSecret: hive-credentials
    s3:
      reference: minio
  metastore:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: hive-credentials
type: Opaque
stringData:
  username: hive
  password: hive
