---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive-test-helper
  labels:
    app: hive-test-helper
spec:
  serviceName: hive-test-helper
  replicas: 1
  selector:
    matchLabels:
      app: hive-test-helper
  template:
    metadata:
      labels:
        app: hive-test-helper
    spec:
      containers:
        - name: hive-test-helper
          image: docker.stackable.tech/stackable/testing-tools:0.2.0-stackable0.0.0-dev
          stdin: true
          tty: true
