---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-postgres-s3
spec:
  version: 3.1.3-stackable0.2.0
  s3:
    reference: minio
  metastore:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          database:
            connString: jdbc:postgresql://postgresql:5432/hive
            user: hive
            password: hive
            dbType: postgres
