= Stackable Operator for Apache Hive
:description: The Stackable Operator for Apache Hive is a Kubernetes operator that can manage Apache Hive metastores. Learn about its features, resources, dependencies and demos, and see the list of supported Hive versions.
:keywords: Stackable Operator, Hadoop, Apache Hive, Kubernetes, k8s, operator, engineer, big data, metadata, storage, query

This is an operator for Kubernetes that can manage https://hive.apache.org[Apache Hive] metastores. 
The Apache Hive metastore (HMS) was originally developed as part of Apache Hive. It stores information on the location of tables and partitions in file and blob storages such as HDFS and S3 and is now used by other tools besides Hive as well to access tables in files.
This Operator does not support deploying Hive itself, but xref:trino:index.adoc[Trino] is recommended as an alternative query engine.

== Required external component: An SQL database

The Hive metastore requires a database to store metadata.
Consult the xref:required-external-components.adoc[required external components page] for an overview of the supported databases and minimum supported versions.

== Why no Hive?

Only the metastore is supported, not Hive itself.
There are several reasons why running Hive on Kubernetes may not be an optimal solution.
The most obvious reason is that Hive requires YARN as an execution framework, and YARN assumes much of the same role as Kubernetes - i.e. assigning resources. 
For this reason we provide xref:trino:index.adoc[Trino] as a query engine in the Stackable Data Platform instead of Hive. Trino still uses the Hive Metastore, hence the inclusion of this operator as well. Trino should offer all the capabilities Hive offers including a lot of additional functionality, such as connections to other data sources.

Additionally, Tables in the HMS can also be accessed from xref:spark-k8s:index.adoc[Apache Spark].

== Supported Versions

The Stackable Operator for Apache Hive currently supports the following versions of Hive:

include::partial$supported-versions.adoc[]
