= First steps
:description: Deploy and verify a Hive metastore cluster with PostgreSQL and MinIO. Follow the setup guide and ensure all pods are ready for operation.

After going through the xref:getting_started/installation.adoc[] section and having installed all the operators, deploy a Hive metastore cluster and it's dependencies.
Afterwards you can <<_verify_that_it_works, verify that it works>>.

== Setup

Several requirements should have already been installed in the xref:getting_started/installation.adoc[Installation guide]:

* xref:commons-operator:index.adoc[Commons Operator]
* xref:secret-operator:index.adoc[Secret Operator]
* xref:listener-operator:index.adoc[Listener Operator]
* xref:hive:index.adoc[Hive Operator]
* PostgreSQL
* MinIO for S3

=== S3Connection

In order to connect Hive to MinIO we need to create several files (or concat in one file).

An xref:concepts:s3.adoc[S3Connection] to connect to MinIO (`hive-minio-s3-connection.yaml`)

[source,yaml]
----
include::example$getting_started/hive-minio-s3-connection.yaml[]
----

Credentials for the S3Connection to log into MinIO (`hive-minio-credentials.yaml`)

[source,yaml]
----
include::example$getting_started/hive-minio-credentials.yaml[]
----

A SecretClass for the credentials to the Minio. The credentials were defined in the installation of Minio (`hive-minio-credentials-secret-class.yaml`)

[source,yaml]
----
include::example$getting_started/hive-minio-credentials-secret-class.yaml[]
----

And lastly the actual Apache Hive cluster definition (`hive-postgres-s3.yaml`). Note how it references the `minio` S3 object

[source,yaml]
----
include::example$getting_started/hive-postgres-s3.yaml[]
----

Once the files are created apply them to the cluster:

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=install-hive]
----

== Verify that it works

Make sure that all the Pods in the StatefulSets are ready:

[source,bash]
----
kubectl get statefulset
----

The output should show all pods ready:

[source,bash]
----
NAME                                 READY   AGE
hive-postgres-s3-metastore-default   1/1     48s
----

For further testing we recommend to use e.g. the python https://github.com/quintoandar/hive-metastore-client[hive-metastore-client]
in order to e.g. create tables or connect a product like Trino via the xref:trino:index.adoc[Stackable Trino Operator].

== What's next

Have a look at the xref:usage-guide/index.adoc[usage guide] to find out more about the features of the Operator.
