= Installation

On this page you will install the Stackable Operator for Apache Hive and all required dependencies. For the installation
of the dependencies and operators you can use Helm or `stackablectl`.

The `stackablectl` command line tool is the recommended way to interact with operators and dependencies. Follow the
xref:management:stackablectl:installation.adoc[installation steps] for your platform if you choose to work with
`stackablectl`.

== Dependencies

First you need to install MinIO and PostgreSQL instances for the Hive metastore. PostgreSQL is required as a database
for Hive's metadata, and MinIO will be used as a data store, which the Hive metastore also needs access to.

There are two ways to install the dependencies:

. Using xref:management:stackablectl:index.adoc[stackablectl]
. Using Helm

WARNING: The dependency installations in this guide are only intended for testing and not suitable for production!

=== stackablectl

`stackablectl` was designed to install Stackable components, but its xref:management:stackablectl:commands/stack.adoc[Stacks]
feature can also be used to install arbitrary Helm Charts. You can install MinIO and PostgreSQL using the Stacks feature
as follows, but a simpler method via Helm is shown <<Helm, below>>.

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=stackablectl-install-minio-postgres-stack]
----

Create a file called `minio-stack.yaml`:

[source,yaml]
----
include::example$getting_started/minio-stack.yaml[]
----

As well as `postgres-stack.yaml`:

[source,yaml]
----
include::example$getting_started/postgres-stack.yaml[]
----

And then reference both files in another file called `stackablectl-hive-postgres-minio-stack.yaml`:

[source,yaml]
----
include::example$getting_started/stackablectl-hive-postgres-minio-stack.yaml[]
----

Also create a `release.yaml` file:

[source,yaml]
----
include::example$getting_started/release.yaml[]
----

The release definition already references the required operators for this Getting Started guide.

Now call `stackablectl` and reference those two files:

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=stackablectl-install-minio-postgres-stack]
----

This will install MinIO and PostgreSQL as defined in the Stacks, as well as the Operators. You can now skip the
<<Stackable Operators>> step that follows next.

TIP: Consult the xref:management:stackablectl:quickstart.adoc[Quickstart] to learn more about how to use `stackablectl`.

=== Helm

In order to install the MinIO and PostgreSQL dependencies via Helm, you have to deploy two charts.

==== Minio ====

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=helm-install-minio]
----

==== PostgresSQL ====

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=helm-install-postgres]
----

After the dependencies are deployed, you can start to install the operators.

== Stackable Operators

There are 2 ways to run Stackable Operators:

. Using xref:management:stackablectl:index.adoc[stackablectl]
. Using Helm

=== stackablectl

Run the following command to install all operators necessary for Apache Hive:

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=stackablectl-install-operators]
----

The tool will show

[source]
----
include::example$getting_started/install-operator-output.txt[tag=stackablectl-install-operators-output]
----

=== Helm

Run the following commands Helm to install the operators via Helm

Add the Stackable Helm repository:

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=helm-add-repo]
----

Then install the Stackable operators:

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=helm-install-operators]
----

Helm will deploy the operators in a Kubernetes Deployment and apply the CRDs for the Apache Hive service (as well as the
CRDs for the required operators). You are now ready to deploy the Apache Hive metastore in Kubernetes.

== What's next

xref:getting_started/first_steps.adoc[Set up an Apache Hive cluster]
