FROM oci.stackable.tech/sandbox/malte/hive:4.2.0-stackable0.0.0-dev

RUN curl -o /stackable/hive-metastore/lib/httpcore5-5.3.1.jar https://repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.3.1/httpcore5-5.3.1.jar
